### ISSUE TITLE
Support protobuf-java 3.2.0

### ISSUE THREAD

**Issue by kevintsai** [os72/protobuf-java-shaded-261#2]
Could you release protobuf-java-shaded-320 as well? Thanks.

**Comment by jonefeewang** [comment]
+1, need this feature, shading protobuf official jar and its generated code

**Comment by os72** [comment]
protobuf 3.x seems to still change so fast, they just released 3.3.0. What do you think

**Comment by kevintsai** [comment]
Since [protoc-jar](https://github.com/os72/protoc-jar) supports 3.2.0, I was thinking it'd be good enough if you can release 3.2.0 for protobuf-java-shaded. if both projects can support 3.3.0 that sounds good.
At least having a 3.x version, I think those people who want to use 2.x and 3.x both version together like me will have benefit from your projects.

**Comment by jonefeewang** [comment]
yes, in my case, we are trying to import gRPC service into our projects,  but lots of them has depended on protobuf 2, we can't proceed except shading all libs using protobuf 2 or we can just shading protobuf3 leaves the legacy libs untouched.

**Comment by os72** [comment]
Okay will look into it

**Comment by os72** [comment]
Would you be willing to contribute? I started, I think I could use some help

**Comment by mpetazzoni** [comment]
@os72 Ping. Do you think you'd be able to release a protobuf-java-shaded-350 for 3.5.0?

Unfortunately even if protoc-jar and protoc-jar-maven-plugin both support 3.5.0, it's not possible to use shading without a protobuf-java-shaded-350.

**Comment by os72** [comment]
Hi @mpetazzoni 
Last time I looked there was some additional complexity with 3.x vs 2.x (forgot the details by now)
I could start looking into it again; would you be able to help?

**Comment by mpetazzoni** [comment]
I tried to give a look yesterday but it didn't seem very trivial and I couldn't get it to work. But I'm also dealing with something I don't understand well, neither do I have the past experience of doing this for previous versions.

**Comment by os72** [comment]
It's basically a big search-replace exercise. Last time I had made some progress, I think the core was done. I can look to restart the effort, but I'm looking for help too. Will keep you posted

**Comment by os72** [comment]
Stay tuned: https://github.com/os72/protobuf-java-shaded-351

**Comment by os72** [comment]
@mpetazzoni @jonefeewang @kevintsai 

This builds and passes all tests now, can you give it a try
https://github.com/os72/protobuf-java-shaded-351
https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protobuf-java-shaded-351/

And I found a shading regression in the latest `protoc-jar`, need to release a patch
https://github.com/os72/protoc-jar

**Comment by mpetazzoni** [comment]
@os72 Looks good to me, I was able to build my project with `protobuf-java-shaded-351` and the 3.5..1.1 version of `protobuf-jar-maven-plugin`.

One question though: the proto files under `google/protobuf/*.proto` end up in the final JAR file in a non-renamed location. Wouldn't this conflict in the final application's classpath if another version of the "normal" protobuf-java library was included?

**Comment by os72** [comment]
@mpetazzoni Yes I had the doubt too. But I don't think it would conflict, the .proto files are only used at codegen time (`option java_package = "com.github.os72.protobuf351"`). This way the .proto imports remain version-independent. What do you think? Is there a scenario where it would break?

**Comment by mpetazzoni** [comment]
Should be fine then. Do you think you can release protobuf351 0.9?

**Comment by os72** [comment]
Yes, I think sometime this week

**Comment by os72** [comment]
Released v0.9
